### ISSUE TITLE
Search: case test_cases/q3/ucs_0_graph.test

### ISSUE THREAD

**Issue by aqaurius6666** [tqlong/ai-course-projects#72]
<img width="644" alt="Screenshot 2023-02-09 at 21 44 19" src="https://user-images.githubusercontent.com/54926438/217844913-42fa7d83-a31f-4c79-b353-debe1e6103d8.png">

Thầy giải đáp câu này giúp em với ạ.
Đáp án của em chỉ khác mỗi chỗ expand. Nhưng mà theo em đọc đồ thị thì cost tới G là 1.5, cost tới C là 2 thì nó phải expand G trước chứ ạ 🤔

**Comment by aqaurius6666** [comment]
@tqlong

**Comment by tqlong** [comment]
Cost tới C là 2+2=4
Cost tới G là 2+1+1.5 = 4.5
